### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by TheJP** [blinkenlights/polychrome#67]
Using docker does not seem to work currently:

```
 => ERROR [builder 13/17] RUN mix assets.deploy                                                                                                         38.1s
------
 > [builder 13/17] RUN mix assets.deploy:
1.213
1.213 11:01:53.765 [debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-linux-x64
32.64
32.64 Rebuilding...
33.21
33.21 Done in 651ms.
33.23
33.23 11:02:25.800 [debug] Downloading esbuild from https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.17.11.tgz
36.86
36.86   ../priv/static/assets/app.js  115.9kb
36.86
36.86 ⚡ Done in 21ms
36.99 Compiling 86 files (.ex)
37.83 warning: unused alias PlaylistScheduler
37.83   lib/octopus/game_scheduler.ex:6
37.83
37.83 warning: unused alias Rep
37.83   lib/octopus/game_scheduler.ex:6
37.83
38.00
38.00 == Compilation error in file lib/octopus/webp.ex ==
38.00 ** (ErlangError) Erlang error: :enoent
38.00     (elixir 1.14.4) lib/system.ex:1060: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/octopus_webp"])
38.00     (rustler 0.29.1) lib/rustler/compiler/config.ex:83: Rustler.Compiler.Config.metadata!/1
38.00     (rustler 0.29.1) lib/rustler/compiler/config.ex:70: Rustler.Compiler.Config.build/1
38.00     (rustler 0.29.1) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
38.00     lib/octopus/webp.ex:4: (module)
------
Dockerfile:55
--------------------
  53 |
  54 |     # compile assets
  55 | >>> RUN mix assets.deploy
  56 |
  57 |     # Compile the release
--------------------
ERROR: failed to solve: process "/bin/sh -c mix assets.deploy" did not complete successfully: exit code: 1
```

**Comment by TheJP** [comment]
I got it to work using asdf now :) Just left the issue because I think the Dockerfile seems to do something incorrectly.

**Comment by Reimerei** [comment]
This is an old Dockerfile and not used anymore. I'll delete it form the repo.
